export const questions = [
	{
		id: "Q1",
		text: "Allez-vous prendre un train ?",
		options: [
			{ text: "Oui", next: "Q2" },
			{ text: "Non", next: "end" },
		],
	},
	{
		id: "Q2",
		text: "Quelle est l'origine de votre déplacement ? (D'où êtes-vous parti pour arriver à la gare ?)",
		options: [
			{ text: "Caen", next: "Q2a" },
			{ text: "Autre commune", next: "Q2_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q2_precision",
		text: "Préciser le nom de la commune :",
		freeText: true,
		next: "Q3",
	},
	{
		id: "Q2a",
		text: "De quelle rue de Caen venez-vous ?",
		streetInput: true,
		freeTextPlaceholder: "Nom de la rue",
		next: "Q3",
	},
	{
		id: "Q3",
		text: "Quel mode de transport avez-vous utilisé pour vous rendre à la gare ?",
		options: [
			{ text: "En voiture – en tant que conducteur", next: "Q3a" },
			{ text: "En voiture – en tant que passager", next: "Q3b" },
			{ text: "En bus", next: "Q3_bus", requiresPrecision: true },
			{ text: "En Tramway", next: "Q3_tram", requiresPrecision: true },
			{ text: "En Taxi/VTC", next: "Q3b" },
			{ text: "En 2 roues Motorisé (Moto, scooter…)", next: "Q3a" },
			{ text: "À pied", next: "Q4" },
			{ text: "À vélo", next: "Q3c" },
			{ text: "En trottinette, Gyropode, Monoroue…", next: "Q3c" },
			{ text: "Autre", next: "Q3_autre", requiresPrecision: true },
		],
	},
	{
		id: "Q3_bus",
		text: "Précisez la ligne de bus empruntée :",
		options: [
			{ text: "Ligne 1 : Caen Chemin Vert ↔ Mondeville Centre Commercial", next: "Q4" },
			{ text: "Ligne 2 : Caen Mémorial ↔ Caen Beaulieu Brazza", next: "Q4" },
			{ text: "Ligne 3 : Carpiquet Aéroport ↔ Ifs Jean Vilar", next: "Q4" },
			{ text: "Ligne 4 : Hérouville Centre Commercial ↔ Ifs Jean Vilar", next: "Q4" },
			{ text: "Ligne 5 : Hérouville Sphère ↔ Caen Théâtre", next: "Q4" },
			{ text: "Ligne 6A : Hérouville Saint-Clair ↔ Caen", next: "Q4" },
			{ text: "Ligne 6B : Hérouville Saint-Clair ↔ Caen", next: "Q4" },
			{ text: "Ligne 7 : Biéville ZA au Village / Cambes Le Parc ↔ Caen Théâtre", next: "Q4" },
			{ text: "Ligne 8 : Hérouville Sphère ↔ Caen Poincaré", next: "Q4" },
			{ text: "Ligne 9 : Saint-Germain Place des Canadiens ↔ Colombelles Mairie", next: "Q4" },
			{ text: "Ligne 10 : Blainville Parc ↔ Mondeville Charlotte Corday", next: "Q4" },
			{ text: "Ligne 11 : Cuverville Champ Picot ↔ Bretteville Koenig", next: "Q4" },
			{ text: "Ligne 12 : Lion-sur-Mer Haut Lion ↔ Caen Gare SNCF", next: "Q4" },
			{ text: "Ligne 30 : Caen Gare SNCF ↔ Mondeville Centre Commercial", next: "Q4" },
			{ text: "Ligne 31 : Troarn Bures ↔ Caen Gare SNCF", next: "Q4" },
			{ text: "Ligne 105 : Caen Gare SNCF ↔ Caen Institut Lemonnier", next: "Q4" },
			{ text: "Ligne 106 : Caen Gare SNCF ↔ Mondeville Paul Langevin", next: "Q4" },
			{ text: "Ligne 107 : Caen Gare SNCF ↔ Caen Lycée Sainte-Ursule", next: "Q4" },
			{ text: "Ligne 134 : Le Castelet Saint-Aignan Mairie ↔ Caen Gare SNCF", next: "Q4" },
			{ text: "Ligne 135 : Le Castelet Saint-Aignan Mairie ↔ Caen Gare SNCF", next: "Q4" },
			{ text: "Autre", next: "Q3_bus_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3_bus_precision",
		text: "Précisez la ligne de bus empruntée :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3_tram",
		text: "Précisez la ligne de Tramway empruntée :",
		options: [
			{ text: "T1", next: "Q4" },
			{ text: "T2", next: "Q4" },
			{ text: "T3", next: "Q4" },
		],
	},
	{
		id: "Q3_autre",
		text: "Précisez le mode de transport utilisé :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3a",
		text: "Où avez-vous stationné votre véhicule ?",
		options: [
			{ text: "Au parking de la gare de Caen P1 (Parking courte durée EFFIA)", next: "Q4" },
			{ text: "Au Parking longue durée P2 (Parking longue durée EFFIA)", next: "Q4" },
			{ text: "Parking INDIGO des Rives de l'Orne", next: "Q4" },
			{ text: "Au parking INDIGO Presqu'ile", next: "Q4" },
			{ text: "Sur une place en voirie au nord de la gare", next: "Q4" },
			{ text: "Sur une place en voirie au sud de la gare", next: "Q4" },
			{ text: "Sur un stationnement privé (box ou place de parking privée)", next: "Q4" },
			{ text: "Autre", next: "Q3a_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3a_precision",
		text: "Précisez l'endroit où vous avez stationné votre véhicule :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3b",
		text: "Où vous êtes-vous fait déposer ?",
		options: [
			{ text: "Au niveau du dépose-minute devant l'entrée du souterrain au nord (Dépose-minute en couloir au nord)", next: "Q4" },
			{ text: "Au niveau du dépose-minute devant le bâtiment voyageur au sud (Toute la Place de la Gare, incluant la rue à double-voie à sens unique et le dépose-taxi)", next: "Q4" },
			{ text: "Sur le parking de la gare (Parking courte durée EFFIA au nord)", next: "Q4" },
			{ text: "Directement sur la rue à proximité de la Gare (HORS Place de la Gare – dépose-minute)", next: "Q4" },
			{ text: "Autre", next: "Q3b_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3b_precision",
		text: "Précisez l'endroit où vous vous êtes fait déposer :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3c",
		text: "Où avez-vous stationné votre vélo/trottinette ?",
		options: [
			{ text: "Sur les arceaux sur le parking de la gare côté nord (Vélopark Gare SNCF)", next: "Q4" },
			{ text: "Sur les arceaux en libre accès (place de la Gare)", next: "Q4" },
			{ text: "Sur les arceaux sur voirie au sud de la Gare (quartier Vaucelles)", next: "Q4" },
			{ text: "Je le transporte avec moi dans le train", next: "Q4" },
			{ text: "Autre", next: "Q3c_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3c_precision",
		text: "Précisez l'endroit où vous avez stationné votre vélo/trottinette :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q4",
		text: "Combien de temps avant le départ de votre train êtes-vous arrivé en gare ?",
		freeText: true,
		next: "Q5",
	},
	{
		id: "Q5",
		text: "Pour ce trajet en train, quelle sera votre gare de destination finale ?",
		options: [
			{ text: "Alençon", next: "Q6" },
			{ text: "Argentan", next: "Q6" },
			{ text: "Audrieu", next: "Q6" },
			{ text: "Avranches", next: "Q6" },
			{ text: "Bayeux", next: "Q6" },
			{ text: "Briouze", next: "Q6" },
			{ text: "Bretteville - Norrey", next: "Q6" },
			{ text: "Carentan", next: "Q6" },
			{ text: "Cherbourg", next: "Q6" },
			{ text: "Château-du-Loir", next: "Q6" },
			{ text: "Coutances", next: "Q6" },
			{ text: "Dol-de-Bretagne", next: "Q6" },
			{ text: "Évreux Normandie", next: "Q6" },
			{ text: "Folligny", next: "Q6" },
			{ text: "Flers", next: "Q6" },
			{ text: "Granville", next: "Q6" },
			{ text: "L'Aigle", next: "Q6" },
			{ text: "Le Mans", next: "Q6" },
			{ text: "Le Molay-Littry", next: "Q6" },
			{ text: "Lison", next: "Q6" },
			{ text: "Lisieux", next: "Q6" },
			{ text: "Mézidon", next: "Q6" },
			{ text: "Paris Saint-Lazare", next: "Q6" },
			{ text: "Pontorson – Mont-Saint-Michel", next: "Q6" },
			{ text: "Rennes", next: "Q6" },
			{ text: "Rouen Rive Droite", next: "Q6" },
			{ text: "Saint-Lô", next: "Q6" },
			{ text: "Tours", next: "Q6" },
			{ text: "Vire Normandie", next: "Q6" },
			{ text: "Autre", next: "Q5_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q5_precision",
		text: "Précisez votre gare de destination finale :",
		freeText: true,
		next: "Q6",
	},
	{
		id: "Q6",
		text: "Quel est le lieu de votre destination finale ?",
		freeText: true,
		freeTextPlaceholder: "Préciser la commune",
		next: "Q7",
	},
	{
		id: "Q7",
		text: "Quel est le motif de votre déplacement en train ?",
		options: [
			{ text: "Je me rends sur mon lieu de travail", next: "Q8" },
			{ text: "Je me rends sur mon lieu d'études", next: "Q8" },
			{ text: "Je rentre à mon domicile principal", next: "Q8" },
			{ text: "Déplacement professionnel", next: "Q8" },
			{ text: "Démarches administratives, RDV médical", next: "Q8" },
			{ text: "Loisirs, tourisme, visite d'un proche ou ami", next: "Q8" },
			{ text: "Autres", next: "Q7_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q7_precision",
		text: "Précisez le motif de votre déplacement :",
		freeText: true,
		next: "Q8",
	},
	{
		id: "Q8",
		text: "A quelle fréquence réalisez-vous ce déplacement en train ?",
		options: [
			{ text: "Tous les jours de la semaine ou presque", next: "Q9" },
			{ text: "1 à 2 fois par semaine", next: "Q9" },
			{ text: "Plusieurs fois par mois (3 à 4 fois)", next: "Q9" },
			{ text: "Occasionnellement (moins d'une fois par mois)", next: "Q9" },
			{ text: "C'est la 1ère fois", next: "Q9" },
		],
	},
	{
		id: "Q9",
		text: "Effectuez-vous l'aller ou le retour de votre déplacement ?",
		options: [
			{ text: "L'aller", next: "Q9a" },
			{ text: "Le retour", next: "Q9b" },
			{ text: "Ni l'un ni l'autre", next: "Q9c" },
		],
	},
	{
		id: "Q9a",
		text: "Quand effectuerez-vous le retour ?",
		freeText: true,
		next: "Q10",
	},
	{
		id: "Q9b",
		text: "Quand avez-vous effectué l'aller ?",
		freeText: true,
		next: "Q10",
	},
	{
		id: "Q9c",
		text: "Quel est le motif de votre présence en gare ?",
		options: [
			{ text: "Je viens récupérer un ou des voyageurs à l'arrivée", next: "Q10" },
			{ text: "J'accompagne un ou des voyageurs au départ", next: "Q10" },
			{ text: "J'achète un billet", next: "Q10" },
			{ text: "Je traverse simplement la gare", next: "Q10" },
			{ text: "Je suis chaland (je fréquente les commerces ou les services de la gare)", next: "Q10" },
			{ text: "Autre", next: "Q9c_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q9c_precision",
		text: "Précisez le motif de votre présence en gare :",
		freeText: true,
		next: "Q10",
	},
	{
		id: "Q10",
		text: "Quel est votre catégorie socio-professionnelle ?",
		options: [
			{ text: "Agriculteur / exploitant", next: "Q11" },
			{ text: "Artisan / commerçant : chef d'entreprise", next: "Q11" },
			{ text: "Cadre / profession intellectuelle supérieure", next: "Q11" },
			{ text: "Profession intermédiaire (ex : technicien, instituteur, infirmier)", next: "Q11" },
			{ text: "Employé(e)", next: "Q11" },
			{ text: "Ouvrier / ouvrière", next: "Q11" },
			{ text: "Étudiant(e)", next: "Q11" },
			{ text: "Retraité(e)", next: "Q11" },
			{ text: "Sans activité professionnelle (au foyer, demandeur d'emploi, etc…)", next: "Q11" },
			{ text: "Autre", next: "Q10_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q10_precision",
		text: "Précisez votre catégorie socio-professionnelle :",
		freeText: true,
		next: "Q11",
	},
	{
		id: "Q11",
		text: "Quel est votre âge ?",
		options: [
			{ text: "Moins de 18 ans", next: "Q12" },
			{ text: "18 – 24 ans", next: "Q12" },
			{ text: "25 – 34 ans", next: "Q12" },
			{ text: "35 – 44 ans", next: "Q12" },
			{ text: "45 – 54 ans", next: "Q12" },
			{ text: "55 – 64 ans", next: "Q12" },
			{ text: "65 ans et plus", next: "Q12" },
		],
	},
	{
		id: "Q12",
		text: "Précisez le genre",
		options: [
			{ text: "Homme", next: "end" },
			{ text: "Femme", next: "end" },
		],
	},
];



// // Liste des communes aux alentours de Caen
// export const communesAutourCaen = [
// 	"Anisy",
// 	"Authie",
// 	"Bénouville",
// 	"Biéville-Beuville",
// 	"Blainville-sur-Orne",
// 	"Bretteville-sur-Odon",
// 	"Cambes-en-Plaine",
// 	"Carpiquet",
// 	"Colombelles",
// 	"Cormelles-le-Royal",
// 	"Cuverville",
// 	"Démouville",
// 	"Épron",
// 	"Fleury-sur-Orne",
// 	"Fontaine-Étoupefour",
// 	"Giberville",
// 	"Hérouville-Saint-Clair",
// 	"Ifs",
// 	"Lion-sur-Mer",
// 	"Louvigny",
// 	"Mathieu",
// 	"Mondeville",
// 	"Ouistreham",
// 	"Saint-Aubin-d'Arquenay",
// 	"Saint-Contest",
// 	"Saint-Germain-la-Blanche-Herbe",
// 	"Verson",
// 	"Villons-les-Buissons",
// ];